name: Deploy Next.js to Hostinger
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      # Create .htaccess file for the build output
      - name: Create .htaccess file
        run: |
          cat > .htaccess << 'EOL'
          # .htaccess file for Next.js static site
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            
            # Handle trailing slashes
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*[^/])$ /$1/ [L,R=301]
          
            # Handle client-side routing
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule ^(.*)$ /index.html [L]
          </IfModule>
          
          # Prevent directory listing
          Options -Indexes
          
          # Set default document
          DirectoryIndex index.html
          
          # Allow access to all files
          <FilesMatch ".*">
            Order Allow,Deny
            Allow from all
          </FilesMatch>
          EOL
      
      - name: Build Next.js
        run: |
          npm run build
      
      - name: Copy .htaccess to build output
        run: |
          cp .htaccess ./out/
      
      # Debug with simple output - no invalid functions
      - name: Debug Secrets
        run: |
          echo "Checking if secrets exist (values will be masked):"
          echo "SSH_HOST: ${{ secrets.SSH_HOST != '' && 'exists' || 'missing' }}"
          echo "SSH_USERNAME: ${{ secrets.SSH_USERNAME != '' && 'exists' || 'missing' }}"
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY != '' && 'exists' || 'missing' }}"
          echo "SSH_TARGET_DIR: ${{ secrets.SSH_TARGET_DIR != '' && 'exists' || 'missing' }}"
          
          # Set explicit environment variables
          echo "REMOTE_HOST=82.25.96.67" >> $GITHUB_ENV
          echo "REMOTE_USER=u995357878" >> $GITHUB_ENV
          echo "REMOTE_PORT=65002" >> $GITHUB_ENV
      
      # Try using a different SSH deployment action
      - name: Deploy to Hostinger via SSH
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: out/
          remote_path: ${{ secrets.SSH_TARGET_DIR || '/home/u995357878/domains/cyrixtechsolutions.com/public_html/' }}
          remote_host: ${{ secrets.SSH_HOST || '82.25.96.67' }}
          remote_port: ${{ secrets.SSH_PORT || '65002' }}
          remote_user: ${{ secrets.SSH_USERNAME || 'u995357878' }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # Fallback to FTP if SSH fails
      - name: Deploy via FTP (Alternative)
        if: ${{ failure() }}  # Only run if the SSH deployment fails
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST || '82.25.96.67' }}
          username: ${{ secrets.FTP_USERNAME || 'u995357878' }}
          password: ${{ secrets.FTP_PASSWORD || 'Cyrix10$' }}
          local-dir: ./out/
          server-dir: ${{ secrets.FTP_SERVER_DIR || '/domains/cyrixtechsolutions.com/public_html/' }}
          dangerous-clean-slate: true
      
      # Simple SSH test as a last resort
      - name: Test SSH Connection
        if: ${{ always() }}  # Run regardless of previous steps
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST || '82.25.96.67' }}
          port: ${{ secrets.SSH_PORT || '65002' }}
          username: ${{ secrets.SSH_USERNAME || 'u995357878' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH connection successful!"
            echo "Current directory: $(pwd)"
            mkdir -p /home/u995357878/domains/cyrixtechsolutions.com/public_html/ || true
            echo "Directory created/verified"